CREATE TABLE [dbo].[fact_orders] (
    [fact_orders_key]                INT             IDENTITY (1, 1) NOT NULL,
    [dim_customers_key]              INT             NOT NULL,
    [dim_order_status_key]           INT             NOT NULL,
    [dim_subscriptions_key]          INT             NOT NULL,
    [dim_coupons_key]                INT             NOT NULL,
    [dim_how_did_you_hear_key]       INT             NOT NULL,
    [dim_how_did_you_hear_other_key] INT             NOT NULL,
    [dim_shipping_key]               INT             NOT NULL,
    [id]                             BIGINT          NOT NULL,
    [reference_number]               BIGINT          NOT NULL,
    [grand_total]                    DECIMAL (28, 6) NULL,
    [subtotal]                       DECIMAL (28, 6) NULL,
    [tax_amount]                     DECIMAL (28, 6) NULL,
    [total_due]                      DECIMAL (28, 6) NULL,
    [total_invoiced]                 DECIMAL (28, 6) NULL,
    [total_item_count]               INT             NULL,
    [total_paid]                     DECIMAL (28, 6) NULL,
    [total_qty_ordered]              INT             NULL,
    [total_refunded]                 DECIMAL (28, 6) NULL,
    [discount_amount]                DECIMAL (28, 6) NULL,
    [order_currency_code]            CHAR (3)        NULL,
    [order_currency_exchange_rate]   DECIMAL (28, 6) NOT NULL,
    [giftcert_amount]                DECIMAL (28, 6) NULL,
    [customer_group_id]              INT             NOT NULL,
    [customer_account_id]            INT             NULL,
    [customer_is_guest]              BIT             NULL,
    [shipping_amount]                DECIMAL (28, 6) NULL,
    [shipping_discount_amount]       DECIMAL (28, 6) NULL,
    [shipping_hidden_tax_amount]     DECIMAL (28, 6) NULL,
    [shipping_incl_tax]              DECIMAL (28, 6) NULL,
    [shipping_invoiced]              DECIMAL (28, 6) NULL,
    [shipping_refunded]              DECIMAL (28, 6) NULL,
    [created_at]                     DATETIME2 (7)   NULL,
    [updated_at]                     DATETIME2 (7)   NULL,
    [order_has_subscription]         BIT             NULL,
    [order_has_ecommerce]            BIT             NULL,
    CONSTRAINT [PK_fact_orders] PRIMARY KEY CLUSTERED ([fact_orders_key] ASC),
    CONSTRAINT [FK_fact_orders_dim_coupons_0x876c293e3f1cb86ffe792d0ddffefc9c] FOREIGN KEY ([dim_coupons_key]) REFERENCES [dbo].[dim_coupons] ([dim_coupons_key]),
    CONSTRAINT [FK_fact_orders_dim_customers_0x8f174bc5ff5ce14339489cf8dc7f7be5] FOREIGN KEY ([dim_customers_key]) REFERENCES [dbo].[dim_customers] ([dim_customers_key]),
    CONSTRAINT [FK_fact_orders_dim_how_did_you_hear_0x97b14e9ca41576a953def2997f123361] FOREIGN KEY ([dim_how_did_you_hear_key]) REFERENCES [dbo].[dim_how_did_you_hear] ([dim_how_did_you_hear_key]),
    CONSTRAINT [FK_fact_orders_dim_how_did_you_hear_other_0x8bfaa4bb9af976916e64700d01844443] FOREIGN KEY ([dim_how_did_you_hear_other_key]) REFERENCES [dbo].[dim_how_did_you_hear_other] ([dim_how_did_you_hear_other_key]),
    CONSTRAINT [FK_fact_orders_dim_order_status_0x79a6dd72358f22f76042f58b6b2c1043] FOREIGN KEY ([dim_order_status_key]) REFERENCES [dbo].[dim_order_status] ([dim_order_status_key]),
    CONSTRAINT [FK_fact_orders_dim_shipping_0x684b2225161db197adf3b8df36e67b33] FOREIGN KEY ([dim_shipping_key]) REFERENCES [dbo].[dim_shipping] ([dim_shipping_key]),
    CONSTRAINT [FK_fact_orders_dim_subscriptions_0xee3b0c157a10f0db89f085ab27d0f9de] FOREIGN KEY ([dim_subscriptions_key]) REFERENCES [dbo].[dim_subscriptions] ([dim_subscriptions_key])
);

