CREATE TABLE [dbo].[staging_orders] (
    [id]                         INT             NULL,
    [reference_number]           INT             NULL,
    [status]                     NVARCHAR (MAX)  NULL,
    [subscription_id]            INT             NULL,
    [state]                      NVARCHAR (MAX)  NULL,
    [grand_total]                DECIMAL (28, 6) NULL,
    [subtotal]                   DECIMAL (28, 6) NULL,
    [tax_amount]                 DECIMAL (28, 6) NULL,
    [total_due]                  DECIMAL (28, 6) NULL,
    [total_invoiced]             DECIMAL (28, 6) NULL,
    [total_item_count]           DECIMAL (28, 6) NULL,
    [total_paid]                 DECIMAL (28, 6) NULL,
    [total_qty_ordered]          INT             NULL,
    [total_refunded]             DECIMAL (28, 6) NULL,
    [discount_amount]            DECIMAL (28, 6) NULL,
    [order_currency_code]        CHAR (3)        NULL,
    [giftcert_amount]            DECIMAL (28, 6) NULL,
    [coupon_code]                NVARCHAR (MAX)  NULL,
    [coupon_rule_name]           NVARCHAR (MAX)  NULL,
    [customer_group_id]          INT             NULL,
    [customer_account_id]        INT             NULL,
    [customer_is_guest]          BIT             NULL,
    [shipping_amount]            DECIMAL (28, 6) NULL,
    [shipping_description]       NVARCHAR (MAX)  NULL,
    [shipping_discount_amount]   DECIMAL (28, 6) NULL,
    [shipping_hidden_tax_amount] DECIMAL (28, 6) NULL,
    [shipping_incl_tax]          DECIMAL (28, 6) NULL,
    [shipping_invoiced]          DECIMAL (28, 6) NULL,
    [shipping_method]            NVARCHAR (MAX)  NULL,
    [shipping_refunded]          DECIMAL (28, 6) NULL,
    [how_did_you_hear]           NVARCHAR (MAX)  NULL,
    [how_did_you_hear_other]     NVARCHAR (MAX)  NULL,
    [created_at]                 DATETIME2 (7)   NULL,
    [updated_at]                 DATETIME2 (7)   NULL,
    [order_has_subscription]     BIT             NULL,
    [order_has_ecommerce]        BIT             NULL,
    [customer_email]             NVARCHAR (320)  NULL,
    [customer_fname]             NVARCHAR (128)  NULL,
    [customer_lname]             NVARCHAR (128)  NULL
);

